### ISSUE TITLE
Skip Geo Location Data

### ISSUE THREAD

**Issue by santhosh244** [awslabs/aws-vpc-flow-log-appender#1]
Hi,

Since we have a limitation on https://freegeoip.net/(i.e 15K requests per hour). Can we skip that geo location check and process the lamba function without errors. 

When we deploy this lamda function in production, we get limit exceed error and it causes invocation errors.

**Comment by santhosh244** [comment]
It has become worse. .Not able to process any flow log. Can you kindly test this dev build again?

**Comment by jkahn117** [comment]
Could you please provide error logs (see CloudWatch).

**Comment by santhosh244** [comment]
Hi,

I could't locate the exact error, but below are few errors in cloudwatch

REPORT RequestId: ba857e10-5e1e-11e7-a377-87034dc7adb0	Duration: 44847.13 ms	Billed Duration: 44900 ms Memory Size: 128 MB	Max Memory Used: 128 MB	
RequestId: ba857e10-5e1e-11e7-a377-87034dc7adb0 Process exited before completing request

If you can point me the error location, I can find them and update so that it would be easy.

**Comment by jkahn117** [comment]
That message indicates that some error was thrown that stopped execution of the function, but not specifically what occurred.  Are you familiar with Lambda / NodeJS? I would suggest adding logging statements or looking at [lambda-toolkit](https://github.com/lucioveloso/lambda-toolkit) to help debug.  Thus far, I have not been able to reproduce in my environment.

**Comment by santhosh244** [comment]
I'm not much familiar with development. But let me give a try and get back to you with some findings
