### ISSUE TITLE
Getting error with deploying cloudformation at step 3 of deploy lambda functions

### ISSUE THREAD

**Issue by mcjayanarayan** [awslabs/aws-vpc-flow-log-appender#3]
error message is as follows:

$ aws cloudformation deploy --template-file app-sam-output.yaml --stack-name vpc-flow-log-appender-dev --capabilities CAPABILITY_IAM --region eu-west-1
Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: User: arn:aws:iam::XXXX:user/YYY is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:eu-west-1:aws:transform/Serverless-2016-10-31

**Comment by jkahn117** [comment]
Please confirm that you have appropriate IAM permissions to create and execute CloudFormation Change Sets. You will also need permission to create IAM and Lambda resources.

**Comment by mcjayanarayan** [comment]
yes i do have the necessary permissions and i verified using IAM policy simulator. Is there a way to do that through GUI (createchangeset operation)

**Comment by jkahn117** [comment]
I would start by confirming that the Access Key currently being used by the CLI is attached to the same IAM User that you use to sign in to the Console. Perhaps there is a more elegant way, but you can use `aws configure` to retrieve the last few digits of the access key and check that against IAM in the console.

**Comment by mcjayanarayan** [comment]
one thing i see is we have IP restrictions in place for IAM access and MFA enabled to use API calls. Will that be causing issues like cloudformation choosing a different IP to execute resources instead of my current IP

**Comment by mcjayanarayan** [comment]
yes the IP restriction is the issue. verified . tried in one of AWS account with no IP restriction
and cloudtrail shows as
Source IP address : cloudformation.amazonaws.com

Thanks for your help
